version: '3.4'
services:

  deluge:   #deluge default password is "deluge" and web link is "ip_address:8112".
    container_name: deluge
    image: linuxserver/deluge:5b398f77-ls22
    restart: unless-stopped
    ports:
      - "127.0.0.1:8112:8112"
    environment:
      - PUID=${PUID} # default user id, defined in .env 
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads/complete:/downloads/complete # complete downloads folder
      - ${ROOT}/downloads/incomplete:/downloads/incomplete # incomplete downloads folder
      - ${ROOT}/config/deluge:/config # config files

  
  jackett: #jackett default web link is "ip_address:9117".
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - "127.0.0.1:9117:9117"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files


  sonarr: #sonarr default web link is "ip_address:8989".
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
      - "127.0.0.1:8989:8989"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/media/tvshows:/tvshows # tv shows folder
      - ${ROOT}/downloads/complete:/downloads/complete # complete downloads folder
      - ${ROOT}/downloads/recycle:/downloads/recycle # recycle folder
  
  radarr: #radarr default web link is "ip_address:7878".
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - "127.0.0.1:7878:7878"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/media/movies:/movies # movies folder
      - ${ROOT}/downloads/complete:/downloads/complete # complete downloads folder
      - ${ROOT}/downloads/recycle:/downloads/recycle # recycle folder
      
  plex-server: #plex default web link is "ip_address:32400/web".
    container_name: plex-server
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
        - PLEX_UID=${PUID} # default user id, defined in .env
        - PLEX_GID=${PGID} # default group id, defined in .env
        - VERSION=docker # Set whether to update plex or not - see Application Setup section.
        - TZ=${TZ} # timezone, defined in .env
        - PLEX_CLAIM=${CLAIM_CODE} #plex claim code
    ports:
      - "127.0.0.1:32400:32400"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ${ROOT}/config/plex/config:/config # plex database
      - ${ROOT}/media/movies:/movies # movies folder
      - ${ROOT}/media/tvshows:/tvshows # tv shows folder
      - ${ROOT}/media/transcode:/transcode # tv shows folder
    
  bazarr: #bazarr default web link is "ip_address:6767".
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    ports:
          - "127.0.0.1:6767:6767"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ}    
    volumes: 
      - ${ROOT}/config/bazarr/config:/config # config files
      - ${ROOT}/media/movies:/movies # movies folder
      - ${ROOT}/media/tvshows:/tvshows # tv shows folder

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ}    
    volumes:
      - ${ROOT}/downloads/complete:/downloads/complete # complete downloads folder
      - ${ROOT}/downloads/incomplete:/downloads/incomplete # incomplete downloads folder
      - ${ROOT}/config/nzbget/config:/config # config files
    ports:
      - "127.0.0.1:6789:6789"
      
  nginx: #nginx reverse proxy.
    container_name: nginx
    image: nginx:stable
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
    environment:
        - PUID=${PUID} # default user id, defined in .env
        - PGID=${PGID} # default group id, defined in .env
        - TZ=${TZ}
    volumes: 
        - /etc/letsencrypt:/etc/letsencrypt # certbot folder
        - ${ROOT}/nginx/nginx.conf:/etc/nginx/nginx.conf # nginx config, create nginx folder and copy nginx.conf and dhpara.pem before running docker compose.
        - ${ROOT}/nginx/dhparam.pem:/etc/nginx/dhparam.pem # nginx dhparam
        - ${ROOT}/nginx/certbot:/etc/nginx/certbot # certbot challange folder
        - ${ROOT}/nginx/auth:/etc/nginx/auth # nginx auth .htpasswd folder, you can find how to create .htpasswd in nginx.conf file.
  